### ISSUE TITLE
Add brittany beautifier for Haskell

### ISSUE THREAD

**Issue by stevenzeck** [Unibeautify/beautifier-brittany#1]
_From @lassik on October 2, 2018 22:50_

**Beautifier Details**
Name: brittany
Link to project/homepage: https://github.com/lspitzner/brittany

**If this is a new beautifier, please fill out the below**
Languages Supported: Haskell
How is it run (node, terminal, etc): external program that reads from stdin and writes to stdout

I made a [repo with Unibeautify support](https://github.com/lassik/beautifier-brittany) by cloning [beautifier-template](https://github.com/Unibeautify/beautifier-template) and copy-pasting stuff from [beautifier-black](https://github.com/Unibeautify/beautifier-black) until I got a test to pass. This is my first ever Node and TypeScript code 😄  Hence I made as few changes as possible to try not to screw anything up. Would be nice if somone could go over them (it's all in one commit) to check for anything that needs to be fixed.

_Copied from original issue: Unibeautify/unibeautify#190_

**Comment by stevenzeck** [comment]
@lassik please create a PR against this repository.

**Comment by stevenzeck** [comment]
I gave you write access.

**Comment by lassik** [comment]
Thanks 🎉 I pushed everything I have. The tests in Travis are going to fail for this beautifier too. I'll look into fixing them, unless you beat me to it 😄

**Comment by lassik** [comment]
brittany has a very clean interface - it's just stdin to stdout, proper use of exit codes, etc. So that's nice :)

**Comment by lassik** [comment]
BTW, do you have a policy of committing everything via PR, even to repos where you have write access?

**Comment by stevenzeck** [comment]
There is no explicit policy, but generally every change should have a PR.  I'm guilty of pushing directly to master for very small changes (such as re-configuring renovate) or the template project.

**Comment by stevenzeck** [comment]
Looks like you just need to install `brittany` in the Travis build.  I don't know how to do that, looks like it requires Haskell specific managers only available when your language is set to Haskell.

**Comment by lassik** [comment]
Closed by #7. We ended up using Stack instead of Cabal.
